Keep rollbar deploy id around for patching

diff --git a/bin/rollbar-deploy b/bin/rollbar-deploy
--- a/bin/rollbar-deploy
+++ b/bin/rollbar-deploy
@@ -15,17 +15,52 @@ if [[ -z ${GIT_COMMIT_AUTHOR+x} ]]; then
   exit 1
 fi
 
-if [[ -z ${DEPLOY_STATUS+x} ]]; then
-  echo 'DEPLOY_STATUS is not set'
+if [[ -z ${1+x} ]]; then
+  echo 'ERROR: status is not specified'
+  echo
+  echo 'Usage: rollbar-deploy [started|succeeded|failed]'
   exit 1
 fi
 
-curl -f https://api.rollbar.com/api/1/deploy/ \
-  -F access_token=${ROLLBAR_ACCESS_TOKEN} \
-  -F status=${DEPLOY_STATUS} \
-  -F environment=production \
-  -F revision=${GIT_COMMIT_SHA} \
-  -F local_username=${GIT_COMMIT_AUTHOR}
+DEPLOY_ID=""
+DEPLOY_ID_FILE=${DEPLOY_ID_FILE:.deploy_id}
 
-echo
-echo "Rollbar notified of deploy: revision=${GIT_COMMIT_SHA} status=${DEPLOY_STATUS}"
+if [[ -f ${DEPLOY_ID_FILE} ]]; then
+  DEPLOY_ID=$(cat ${DEPLOY_ID_FILE})
+fi
+
+DEPLOY_STATUS="${1}"
+
+case ${DEPLOY_STATUS} in
+  started)
+    DEPLOY_ID=$(curl -f https://api.rollbar.com/api/1/deploy/ \
+      -F access_token=${ROLLBAR_ACCESS_TOKEN} \
+      -F status=started \
+      -F environment=production \
+      -F revision=${GIT_COMMIT_SHA} \
+      -F local_username=${GIT_COMMIT_AUTHOR} | jq -r '.data.deploy_id')
+    echo $DEPLOY_ID > ${DEPLOY_ID_FILE}
+    echo
+    echo "Rollbar notified of deploy: deploy_id=${DEPLOY_ID} revision=${GIT_COMMIT_SHA} status=${DEPLOY_STATUS}"
+    ;;
+  succeeded)
+    curl -f -XPATCH https://api.rollbar.com/api/1/deploy/${DEPLOY_ID} \
+      -F access_token=${ROLLBAR_ACCESS_TOKEN} \
+      -F status=succeeded
+    echo
+    echo "Rollbar deploy updated: id=${DEPLOY_ID} status=${DEPLOY_STATUS}"
+    ;;
+  failed)
+    curl -f -XPATCH https://api.rollbar.com/api/1/deploy/${DEPLOY_ID} \
+      -F access_token=${ROLLBAR_ACCESS_TOKEN} \
+      -F status=failed
+    echo
+    echo "Rollbar deploy updated: id=${DEPLOY_ID} status=${DEPLOY_STATUS}"
+    ;;
+  *)
+    echo "Unsupported DEPLOY_STATUS: $DEPLOY_STATUS"
+    exit 1
+  ;;
+esac
+
+
